services:

  apigateway:
    build: ./apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - userservice
      - authservice
      - orderservice

  userservice:
    build: ../inno-userservice/userservice
    container_name: userservice
    ports:
      - "8081:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_USER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST_USER}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - user-db
      - user-redis

  authservice:
    build: ../inno-authservice/authservice
    container_name: authservice
    ports:
      - "8082:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_AUTH}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_EXPIRATION_MINS: ${ACCESS_EXPIRATION_MINS}
      REFRESH_EXPIRATION_MINS: ${REFRESH_EXPIRATION_MINS}
      USERSERVICE_URL: ${USERSERVICE_URL}
    depends_on:
      - auth-db

  orderservice:
    build: ../inno-orderservice/orderservice
    container_name: orderservice
    ports:
      - "8083:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_ORDER}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST_ORDER}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      USERSERVICE_URL: ${USERSERVICE_URL}
    depends_on:
      - order-db
      - order-redis

  paymentservice:
    build: ../inno-paymentservice/paymentservice
    container_name: paymentservice
    ports:
      - "8084:8080"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://payment-db:27017/paymentdb?replicaSet=rs0
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST_PAYMENT}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      JWT_SECRET: ${JWT_SECRET}
      RANDOM_NUMBER_API_URL: "https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new"
    depends_on:
      - payment-db
      - payment-redis
      - kafka

  user-db:
    image: postgres:16
    container_name: userservice_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - user_db_data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16
    container_name: authservice_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: orderservice_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_ORDER}
    ports:
      - "5434:5432"
    networks:
      - app-network
    volumes:
      - order_db_data:/var/lib/postgresql/data

  payment-db:
    image: mongo:7
    container_name: payment-db
    restart: always
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: paymentdb
    networks:
      - app-network
    volumes:
      - payment_db_data:/data/db

  user-redis:
    image: redis:7
    container_name: userservice_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  order-redis:
    image: redis:7
    container_name: orderservice_redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app-network

  payment-redis:
    image: redis:7
    container_name: paymentservice_redis
    restart: always
    ports:
      - "6381:6379"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

volumes:
  user_db_data:
  auth_db_data:
  order_db_data:
  payment_db_data:

networks:
  app-network:
    external: true