spring.application.name=apigateway

jwt.secret=${JWT_SECRET}

auth.service.uri = ${AUTH_SERVICE_URI:authservice/api/v1/auth/**}
auth.service.docs = ${AUTH_SERVICE_DOCS:authservice/v3/api-docs}
user.service.docs = ${USER_SERVICE_DOCS:userservice/v3/api-docs}
order.service.docs = ${ORDER_SERVICE_DOCS:orderservice/v3/api-docs}
payment.service.docs = ${PAYMENT_SERVICE_DOCS:paymentservice/v3/api-docs}

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

auth.service.url=${AUTHSERVICE_URL:http://authservice:8080}

logging.level.com.innowise.apigateway=DEBUG